# Automatically generated by Updater v1.0
# @author Daniel J. Finnegan

import shutil, os, os.path, sys
from subprocess import call

if __name__ == '__main__':
	# First, build Updater
	print ('Building Updater...')

	project_root = os.getcwd()
	
	sys.path.append(os.path.join(project_root, 'updater', 'scripts'))
	os.chdir(os.path.join(project_root, 'updater', 'scripts'))
	shutil.rmtree('build', ignore_errors=True)
	shutil.rmtree('dist', ignore_errors=True)
	os.mkdir('build')
	os.mkdir('dist')

	from builder import build_project
	build_project.build_full_package(os.path.join(project_root, 'updater'))
	os.chdir(project_root)

	# Now build the installer
	print ('Building Updater\'s installer...')
	shutil.rmtree('bin', ignore_errors=True)
	
	os.mkdir('bin')
	os.chdir('bin')
	call(['cmake', '..'])
	call(['cmake', '--build', '.'])
